import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from 'next/link'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>








        <div style={{ flexDirection: "row", justifyContent: "space-between" }}>


      <Link  href={'/aboutus'} className="headermenu">  about us </Link>

<Link  href={'/contactus'} className="headermenu">  contact us </Link>

<Link  href={'/styleguide'} className="headermenu">  Style Guide</Link>


          <button style={{ background: "red", padding: "10px", color: "#fff" }} className="hiIOS"> 
            App Store
          </button>

          <button
            style={{ background: "#000", padding: "10px", color: "#fff" }}
            className="hiAndroid" >
            play store 
          </button>

<Link  href={'/demo1'}>  demo1</Link>

<Link  href={'/demo2'}>  demo2</Link>




<Link  href={'/specialpage'} className="idmee">special pagesss</Link>


<Link  href={'/tracking1'} >Tracking1</Link>


<Link  href={'/allbuttons'} >Tracki All buttons</Link>




        </div>
      </main>
    </>
  );
}
